name: pruebas hola mundo docker

on:
    push:
        branches: [ main ]
jobs:
        build:
            runs-on: ubuntu-latest
            steps:
                - name: Paso 1 - Checkout Repositorio
                  uses: actions/checkout@v4

                - name : Paso 2 - Login Docker Hub
                  uses: docker/login-action@v2
                  with:
                    username: ${{ secrets.DOCKER_TOKEN }} 
                    password: ${{ secrets.DOCKER_USERNAME }} 



